version: "3.6"
services:
  db:
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    image: "postgres:11-alpine"
    restart: always
    volumes:
      - "${PWD}/pgdata:/var/lib/postgresql/data"
  web:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: build #develop
    depends_on:
      - db
    environment:
      MIX_ENV: dev
    env_file:
      - ${PWD}/code/.env
    ports:
      - "4000:4000"
    volumes:
      - ${PWD}/code:/app
# volumes:
#   ${PWD}/pgdata:
